name: Build and Validate

on:
  push:
    branches: [ main ]
    tags-ignore: [ v* ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      working-directory: merge-rs
    - name: Run tests
      run: cargo test --verbose
      working-directory: merge-rs
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
      working-directory: merge-rs
    - name: Run audit
      run: cargo audit --deny warnings --deny unmaintained --deny unsound --deny yanked
      working-directory: merge-rs
